// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Ask(arg1:string):Promise<main.Answer>;

export function IsAIEnabled():Promise<boolean>;
