// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contract} from '../models';
import {main} from '../models';

export function Ask(arg1:string):Promise<contract.Answer>;

export function GetStatus():Promise<main.AIStatus>;

export function IsAIEnabled():Promise<boolean>;

export function SaveAIConfig(arg1:string,arg2:string,arg3:string):Promise<void>;
