// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['main']['IndexService']['GetStatus']();
}

export function Index(arg1) {
  return window['go']['main']['IndexService']['Index'](arg1);
}
