// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNote(arg1, arg2, arg3) {
  return window['go']['main']['NoteService']['CreateNote'](arg1, arg2, arg3);
}

export function GetNote(arg1) {
  return window['go']['main']['NoteService']['GetNote'](arg1);
}

export function GetNoteContent(arg1) {
  return window['go']['main']['NoteService']['GetNoteContent'](arg1);
}

export function GetNotesByProject(arg1) {
  return window['go']['main']['NoteService']['GetNotesByProject'](arg1);
}

export function GetProjects() {
  return window['go']['main']['NoteService']['GetProjects']();
}

export function GetRecent(arg1) {
  return window['go']['main']['NoteService']['GetRecent'](arg1);
}

export function SaveNote(arg1, arg2) {
  return window['go']['main']['NoteService']['SaveNote'](arg1, arg2);
}

export function Search(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['NoteService']['Search'](arg1, arg2, arg3, arg4, arg5, arg6);
}
