// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNote(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetNote(arg1:string):Promise<main.Note>;

export function GetNoteContent(arg1:string):Promise<string>;

export function GetNotesByProject(arg1:string):Promise<Array<main.SearchResult>>;

export function GetProjects():Promise<Array<string>>;

export function GetRecent(arg1:number):Promise<Array<main.SearchResult>>;

export function SaveNote(arg1:string,arg2:string):Promise<void>;

export function Search(arg1:string,arg2:string,arg3:string):Promise<Array<main.SearchResult>>;
