// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function StartServer(arg1:string):Promise<void>;

export function StopServer():Promise<void>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function GetAuthToken():Promise<string>;

export function IsAuthValid(arg1:string):Promise<boolean>;

export function GetInboxCount():Promise<number>;

export function GetRecentCaptures(arg1:number):Promise<main.CaptureInfo[]>;
