// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetStatus():Promise<main.VaultStatus>;

export function GetVaultPath():Promise<string>;

export function InitVault(arg1:string):Promise<void>;

export function IsVault(arg1:string):Promise<boolean>;

export function OpenVault(arg1:string):Promise<void>;

export function SelectFolder():Promise<string>;
