// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['main']['VaultService']['GetStatus']();
}

export function GetVaultPath() {
  return window['go']['main']['VaultService']['GetVaultPath']();
}

export function InitVault(arg1) {
  return window['go']['main']['VaultService']['InitVault'](arg1);
}

export function IsVault(arg1) {
  return window['go']['main']['VaultService']['IsVault'](arg1);
}

export function OpenVault(arg1) {
  return window['go']['main']['VaultService']['OpenVault'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['VaultService']['SelectFolder']();
}
